services:
  mysql:
    image: mysql:8
    container_name: stx-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stx_freelance
    network_mode: host
    volumes:
      - stx_mysql_data:/var/lib/mysql

volumes:
  stx_mysql_data: