[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
# It is strongly suggested to use encrypted mnemonics to avoid putting
# seed phrases directly into TOML files.  To do so, run:
#
#     clarinet deployments encrypt
#
# Enter your seed phrase and a password, then paste the encrypted mnemonic here.
#
# Otherwise, use the mnemonic field below:
mnemonic = "3c8mawiZ7eVZYfUK4yg99LDL7nR6bAoYH8uLbUzyyodt1LLjPjEhwsQswCCnFUMUYc2HsKEEzDnb7FhrBQw1UrLFAC5eRBTTK2NhFhAS79ccJA4yhQqrNhpXwQ8aL3dA7RFeP6ybFkN4HyL6ZA3kiwEcSYH4zxxrTAf9uPBGU8vt2FJcKzTSRNnCG7G8TCZk6xhwA7XR4ppBmEUXDwXDmXrsJNGQrSTnktNgryF6ufLiWRwmE5tL4"
