[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
# It is strongly suggested to use encrypted mnemonics to avoid putting
# seed phrases directly into TOML files.  To do so, run:
#
#     clarinet deployments encrypt
#
# Enter your seed phrase and a password, then paste the encrypted mnemonic here.
#
# Otherwise, use the mnemonic field below:
encrypted_mnemonic = "4YapvsZ2KKTFUn71m6NMqCj46B8WUm7CeB5YTozZFSZQfGurJMDfQkAMAd9vyuHK72cfWt2R6DQRq665payaDjYBP6VYTXzy1DXgGMq7XfWFQUWEcKocG4E8zg1QyuAYxTinLV1rJzF8qkBwUcsfsKHBJrooFQzTNVxgxw3VMvDkCNn5ZqP62TaUp4qPuoXSUqQXr9Qc8BJa58ocjSSMZegHf2mN67ZRCQwpnwemPmVkUYbHf4zDh"
derivation_path = "m/44'/5757'/0'/0/0"